#--- Template for packaging stan models -----------------------------------------

# mlysy@uwaterloo.ca, August 2016.

#--- package-specific settings --------------------------------------------------

# package name.  there's probably a better way to obtain this...
pkg.name <- "MADPop"

# names of stan files, without .stan extension.
# each of these should be located in the inst/stan directory.
stan.names <- c("HardyWeinberg", "DirichletMultinomial")

# optional: corresponding R object names.  That is, the stan code will be
# compiled into an R object of type stanfit with these names.
# If not specified defaults to stan.names.
R.names <- c("HW.mod", "hUM.mod")

#--- stan setup -----------------------------------------------------------------

# append -stan to package name to avoid name conflicts
pkg.name <- paste0(pkg.name, "-stan.RData")
# stan models are stored in inst/stan/{pkg.name}-stan.RData
# load these models
if(file.exists(file.path("inst", "stan", pkg.name))) {
  load(file.path("inst", "stan", pkg.name))
}

# compiles stan.name into a stanfit object if it doesn't already exist
# this is checked by supplying stan.mod and checking if its c++ code is
# identical to that generated by stan.name
stan_model_full <- function(stan.name, stan.mod = NULL) {
  fl <- file.path("inst", "stan", stan.name)
  st <- stanc_builder(file = fl)
  if(!is.null(stan.mod) &&
     (stan.mod@model_cpp$model_cppcode == st$cppcode)) {
    md <- stan.mod
  } else {
    md <- stan_model(stanc_ret = st)
  }
  md
}

#--- compile models -------------------------------------------------------------

message("--- COMPILING STAN CODE ---")
for(ii in 1:length(stan.names)) {
  message(stan.names[ii], ".stan (", ii, "/", length(stan.names), ")")
  assign(R.names[ii],
         value = stan_model_full(paste0(stan.names[ii], ".stan"),
           get0(R.names[ii])))
}
message("---------- DONE -----------")

# save stanfit object in inst/stan/{pkg.name}-stan.RData
# file should always exist...
if(file.exists(file.path("inst", "stan", pkg.name))) {
  save(list = R.names, file = file.path("inst", "stan", pkg.name))
}
# cleanup.  should be a way to do this without cluttering package objects
rm(stan.names, R.names, pkg.name, ii, stan_model_full)
