# created by devtools.stan.
# Please do not edit by hand.

# compiles stan.name into a stanfit object if it doesn't already exist
# this is checked by supplying stan.mod and checking if its c++ code is
# identical to that generated by stan.name
stan_model_full <- function(stan.name, stan.mod = NULL) {
  fl <- file.path("inst", "stan", stan.name)
  st <- stanc_builder(file = fl)
  if(!is.null(stan.mod) &&
     (stan.mod@model_cpp$model_cppcode == st$cppcode)) {
    md <- stan.mod
  } else {
    md <- stan_model(stanc_ret = st)
  }
  md
}

#--- setup names ----------------------------------------------------------------

# package name.  automatically set by use_rstan
pkg.name <- "MADPop"
# append -stan to package name to avoid name conflicts
pkg.name <- paste0(pkg.name, "-stan.RData")

# stan names, without extension.  obtained from inst/stan
stan.names <- c("DirichletMultinomial")

# R names. obtained from [[devtools.stan::export]] tags
# the stan code will be compiled into stanmodel objects with these names.
R.names <- c("hUM.mod")


#--- compile models -------------------------------------------------------------

# stan models are stored in inst/stan/{pkg.name}-stan.RData
# load these models
if(file.exists(file.path("inst", "stan", pkg.name))) {
  load(file.path("inst", "stan", pkg.name))
}

message("--- COMPILING STAN CODE ---")
for(ii in 1:length(stan.names)) {
  message(stan.names[ii], ".stan",
          " -> ", R.names[ii], ".R (", ii, "/", length(stan.names), ")")
  assign(R.names[ii],
         value = stan_model_full(paste0(stan.names[ii], ".stan"),
           get0(R.names[ii])))
}
message("---------- DONE -----------")

# save stanfit object in inst/stan/{pkg.name}-stan.RData
# _ONLY_ if .RData doesn't exist.
# this should only be the case when the package is installed from source,
# since only then is the .RData deleted via .Rbuildignore
if(file.exists(file.path("inst", "stan", pkg.name))) {
  save(list = R.names, file = file.path("inst", "stan", pkg.name))
}

#--- cleanup --------------------------------------------------------------------

# TODO: should be a way to do this without cluttering package objects...
rm(stan.names, R.names, pkg.name, ii, stan_model_full)
